{% set name = "Panoply" %}
{% set version = "5.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.giss.nasa.gov/tools/panoply/download/PanoplyJ-{{ version }}.tgz
  sha256: 0d61f49e080f5f0b356553cf4fa107d5e75ef6916e13e043e2470b5171f8a379

build:
  number: 0
  noarch: generic

requirements:
  build:
    - dos2unix
  run:
    - openjdk >=11
    - menuinst >=2.2

test:
  commands:
    - test -f $PREFIX/bin/panoply
    - test -f $PREFIX/bin/panoply.bat
    - test -f $PREFIX/bin/panoplycl
    - test -f $PREFIX/bin/panoplycl.bat
    - ncj-panoply-ncdump
    - ncj-panoply-nccopy
    - ncj-panoply-nccompare
    - ncj-panoply-bufrsplitter
    - ncj-panoply-cfpointwriter
    - ncj-panoply-gribcdmindex
    - ncj-panoply-featurescan
    - ncj-panoply-catalogcrawler

about:
  home: https://www.giss.nasa.gov/tools/panoply/
  summary: Panoply plots geo-referenced and other arrays from netCDF, HDF, GRIB, and other datasets.
  license: Unlicense
  license_file: README.txt
  doc_url: https://www.giss.nasa.gov/tools/panoply/help/
  dev_url: https://www.giss.nasa.gov/tools/panoply/credits.html

extra:
  recipe-maintainers:
    - cofinoa
    - scharlton2
